name: Deploy RADocs

on: workflow_dispatch

jobs:
  Deploy-Documentation-Site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material
          pip install git+https://github.com/cmitu/mkdocs-altlink-plugin
          pip install mdx_truly_sane_lists
      - name: Deploying the documentation website...
        run: |
          git config user.name "${{ github.actor }}"
          git config user.username "${{ github.actor }}"
          bash generate-docs.sh

